#!/usr/bin/python3

def raise_exception():

    x = "block"
    y = 85
    z = x + y
